# Generated by Django 4.1.3 on 2022-11-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_likes_follows_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='dislike_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
