# Generated by Django 4.1.3 on 2022-11-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_likes_like_posts_dislike_num_posts_like_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='network.posts'),
        ),
    ]
